use std::sync::{Arc, Mutex};

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    Buffer, Context,
    remote_memory::{ReadSource, WriteTarget},
};

use super::{Client, ReadAttachment};

/// A client wrapper that attaches registered buffers to RPC calls.
///
/// Created via [`Client::with_read_buffers`] /
/// [`Client::with_write_buffers`]. Implements the same service traits as
/// `Client` (generated by the `#[service]` macro).
///
/// # Read buffers
///
/// The attached read buffers form the request's *read space*, advertised
/// in the request metadata; the server reads from it via
/// [`Context::remote_read`](crate::Context::remote_read). They are
/// owned by this wrapper and kept immutable while pending reads hold them.
///
/// # Write buffers
///
/// The attached write buffers form the request's *write space*; ownership
/// moves into the call, the memory stays pinned until the call resolves,
/// and the server writes into it via
/// [`Context::remote_write`](crate::Context::remote_write). Methods
/// returning `Result<WithBuffers<T>, E>` deliver all of them back through
/// the return value; after a failed call, recover them with
/// [`take_write_buffers`](Self::take_write_buffers).
///
/// # Examples
///
/// ```rust,ignore
/// // Server reads from the client's buffers:
/// let rsp = client.with_read_buffers(bufs).upload(&ctx, &req).await?;
///
/// // Upload and download in a single call:
/// let (rsp, out) = client
///     .with_read_buffers(src_bufs)
///     .with_write_buffers(dst_bufs)
///     .transform(&ctx, &req)
///     .await?
///     .into_parts();
/// ```
pub struct ClientWithBuffers<'a> {
    client: &'a Client,
    read_source: Option<Arc<ReadSource>>,
    read_charge_bytes: Option<u64>,
    write_buffers: Mutex<Option<Vec<Buffer>>>,
}

impl<'a> ClientWithBuffers<'a> {
    /// Creates an empty wrapper; see [`Client::with_read_buffers`] /
    /// [`Client::with_write_buffers`].
    pub(super) fn new(client: &'a Client) -> Self {
        Self {
            client,
            read_source: None,
            read_charge_bytes: None,
            write_buffers: Mutex::new(None),
        }
    }

    /// Replaces the request's read space with one owned buffer.
    #[must_use]
    pub fn with_read_buffer(self, buffer: Buffer) -> Self {
        self.with_read_buffers(vec![buffer])
    }

    /// Replaces the request's read space with owned buffers.
    #[must_use]
    pub fn with_read_buffers(mut self, buffers: Vec<Buffer>) -> Self {
        self.read_source = (!buffers.is_empty()).then(|| Arc::new(ReadSource { buffers }));
        self
    }

    /// Returns an immutable view of the attached source buffers.
    pub fn read_buffers(&self) -> &[Buffer] {
        self.read_source
            .as_ref()
            .map_or(&[], |source| source.buffers.as_slice())
    }

    /// Recovers the source buffers when no pending request or local reader
    /// still holds them. On `None`, the wrapper retains its source so the
    /// caller can retry after those operations finish.
    pub fn take_read_buffers(&mut self) -> Option<Vec<Buffer>> {
        match Arc::try_unwrap(self.read_source.take()?) {
            Ok(source) => Some(source.buffers),
            Err(source) => {
                self.read_source = Some(source);
                None
            }
        }
    }

    /// Overrides the SEND bandwidth charge for an internal request whose
    /// peer will read only part of the advertised read space.
    #[cfg(feature = "rdma")]
    pub(crate) fn with_read_charge_bytes(mut self, bytes: u64) -> Self {
        self.read_charge_bytes = Some(bytes);
        self
    }

    /// Attaches the request's write buffers (replacing any previous set).
    #[must_use]
    pub fn with_write_buffers(self, buffers: Vec<Buffer>) -> Self {
        *self.write_buffers.lock().unwrap() = Some(buffers);
        self
    }

    /// Recovers the attached write buffers after a *failed* call (they are
    /// consumed by a successful one and returned through its
    /// `WithBuffers` result instead). Returns `None` when nothing is
    /// recoverable — e.g. a transfer is still in flight; the buffers then
    /// drop back to the pool once it finishes.
    pub fn take_write_buffers(&self) -> Option<Vec<Buffer>> {
        self.write_buffers.lock().unwrap().take()
    }

    /// Makes an RPC request with the configured buffers.
    pub(crate) async fn ruapc_request<Req, Rsp, E>(
        &self,
        ctx: &Context,
        req: &Req,
        write_buffers_slot: Option<&mut Vec<Buffer>>,
        method_name: &str,
    ) -> std::result::Result<Rsp, E>
    where
        Req: Serialize + JsonSchema,
        Rsp: for<'c> Deserialize<'c> + JsonSchema,
        E: std::error::Error + From<crate::Error> + for<'c> Deserialize<'c>,
    {
        let mut target = match self.write_buffers.lock().unwrap().take() {
            Some(buffers) => Some(WriteTarget::new(buffers)?),
            None => None,
        };
        let mut returned: Vec<Buffer> = Vec::new();
        let result = self
            .client
            .ruapc_request(
                ctx,
                req,
                ReadAttachment::new(self.read_source.as_ref(), self.read_charge_bytes),
                &mut target,
                Some(&mut returned),
                method_name,
            )
            .await;
        if result.is_ok() {
            if let Some(slot) = write_buffers_slot {
                *slot = returned;
            }
        } else {
            // On failure, make the write buffers recoverable through
            // `take_write_buffers` whenever nothing keeps them pinned:
            // either the request never consumed the target (pre-wire
            // failure) or an error *response* handed the buffers back.
            let recovered = match target.take() {
                Some(arc) => WriteTarget::try_into_buffers(arc),
                None if !returned.is_empty() => Some(returned),
                None => None,
            };
            if let Some(buffers) = recovered {
                *self.write_buffers.lock().unwrap() = Some(buffers);
            }
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn forgotten_request_cannot_release_an_active_read_source() {
        use crate::{
            MsgMeta, SocketPoolConfig,
            services::{DescribeRequest, ReflectionService as _},
        };
        use std::{
            future::Future,
            task::{Context as TaskContext, Poll, Waker},
        };

        let base = Context::create(&SocketPoolConfig::default()).unwrap();
        let (sender, _receiver) = tokio::sync::mpsc::channel(1);
        let ctx = Context::server_ctx(
            &base.state,
            crate::Socket::TCP(crate::tcp::TcpSocket::new(sender)),
            MsgMeta {
                timeout_ms: 30_000,
                ..Default::default()
            },
        );
        let mut buffer = ctx.state.buffer_pool.allocate(16).unwrap();
        buffer.set_len(4);
        buffer.copy_from_slice(b"data");
        let client = Client::default();
        let mut wrapper = client.with_read_buffer(buffer);
        let request_payload = DescribeRequest::default();
        let mut request = Box::pin(wrapper.describe(&ctx, &request_payload));
        assert!(matches!(
            request
                .as_mut()
                .poll(&mut TaskContext::from_waker(Waker::noop())),
            Poll::Pending
        ));
        // Forgetting a future is safe Rust: source ownership must not depend on
        // the request's Drop running before the wrapper can be reused/dropped.
        std::mem::forget(request);
        assert!(wrapper.take_read_buffers().is_none());
        let source = ctx.state.waiter.read_source(0).unwrap();
        ctx.state
            .waiter
            .expire(std::time::Instant::now() + std::time::Duration::from_secs(60));
        assert!(wrapper.take_read_buffers().is_none());
        assert_eq!(
            source.read_inline(&[crate::CopyOp::new(0, 0, 4)]).unwrap(),
            b"data"
        );
        drop(source);
        assert_eq!(&wrapper.take_read_buffers().unwrap()[0][..], b"data");
    }

    #[tokio::test]
    async fn test_write_buffers_recoverable_after_failed_call() {
        use crate::{
            SocketPoolConfig,
            services::{DescribeRequest, ReflectionService as _},
        };
        let ctx = crate::Context::create(&SocketPoolConfig::default()).unwrap();
        let client = Client::default();
        let mut buf = ctx.state.buffer_pool.allocate(64 * 1024).unwrap();
        buf.set_len(16);
        let wrapper = client.with_write_buffers(vec![buf]);
        // Invalid endpoint: the call fails before reaching the wire.
        let result = wrapper.describe(&ctx, &DescribeRequest::default()).await;
        assert!(result.is_err());
        let recovered = wrapper.take_write_buffers().expect("buffers recoverable");
        assert_eq!(recovered.len(), 1);
        assert_eq!(recovered[0].len(), 16);
    }
}
