use std::sync::Mutex;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{Buffer, Context, core::WriteTarget};

use super::Client;

/// A client wrapper that attaches registered buffers to RPC calls.
///
/// Created via [`Client::with_read_buffers`] /
/// [`Client::with_write_buffers`]. Implements the same service traits as
/// `Client` (generated by the `#[service]` macro).
///
/// # Read buffers
///
/// The attached read buffers form the request's *read space*, advertised
/// in the request metadata; the server reads from it via
/// [`Context::remote_read`](crate::Context::remote_read). They remain
/// borrowed by the caller.
///
/// # Write buffers
///
/// The attached write buffers form the request's *write space*; ownership
/// moves into the call, the memory stays pinned until the call resolves,
/// and the server writes into it via
/// [`Context::remote_write`](crate::Context::remote_write). Methods
/// returning `Result<WithBuffers<T>, E>` deliver all of them back through
/// the return value; after a failed call, recover them with
/// [`take_write_buffers`](Self::take_write_buffers).
///
/// # Examples
///
/// ```rust,ignore
/// // Server reads from the client's buffers:
/// let rsp = client.with_read_buffers(&bufs).upload(&ctx, &req).await?;
///
/// // Upload and download in a single call:
/// let (rsp, out) = client
///     .with_read_buffers(&src_bufs)
///     .with_write_buffers(dst_bufs)
///     .transform(&ctx, &req)
///     .await?
///     .into_parts();
/// ```
pub struct ClientWithBuffers<'a> {
    client: &'a Client,
    read_buffers: Vec<&'a Buffer>,
    write_buffers: Mutex<Option<Vec<Buffer>>>,
}

impl<'a> ClientWithBuffers<'a> {
    /// Creates an empty wrapper; see [`Client::with_read_buffers`] /
    /// [`Client::with_write_buffers`].
    pub(super) fn new(client: &'a Client) -> Self {
        Self {
            client,
            read_buffers: Vec::new(),
            write_buffers: Mutex::new(None),
        }
    }

    /// Appends one buffer to the request's read space.
    #[must_use]
    pub fn with_read_buffer(mut self, buffer: &'a Buffer) -> Self {
        self.read_buffers.push(buffer);
        self
    }

    /// Appends buffers to the request's read space.
    #[must_use]
    pub fn with_read_buffers(mut self, buffers: &'a [Buffer]) -> Self {
        self.read_buffers.extend(buffers.iter());
        self
    }

    /// Attaches the request's write buffers (replacing any previous set).
    #[must_use]
    pub fn with_write_buffers(self, buffers: Vec<Buffer>) -> Self {
        *self.write_buffers.lock().unwrap() = Some(buffers);
        self
    }

    /// Recovers the attached write buffers after a *failed* call (they are
    /// consumed by a successful one and returned through its
    /// `WithBuffers` result instead). Returns `None` when nothing is
    /// recoverable — e.g. a transfer is still in flight; the buffers then
    /// drop back to the pool once it finishes.
    pub fn take_write_buffers(&self) -> Option<Vec<Buffer>> {
        self.write_buffers.lock().unwrap().take()
    }

    /// Makes an RPC request with the configured buffers.
    pub(crate) async fn ruapc_request<Req, Rsp, E>(
        &self,
        ctx: &Context,
        req: &Req,
        write_buffers_slot: Option<&mut Vec<Buffer>>,
        method_name: &str,
    ) -> std::result::Result<Rsp, E>
    where
        Req: Serialize + JsonSchema,
        Rsp: for<'c> Deserialize<'c> + JsonSchema,
        E: std::error::Error + From<crate::Error> + for<'c> Deserialize<'c>,
    {
        let mut target = match self.write_buffers.lock().unwrap().take() {
            Some(buffers) => Some(WriteTarget::new(buffers)?),
            None => None,
        };
        let mut returned: Vec<Buffer> = Vec::new();
        let result = self
            .client
            .ruapc_request(
                ctx,
                req,
                &self.read_buffers,
                &mut target,
                Some(&mut returned),
                method_name,
            )
            .await;
        if result.is_ok() {
            if let Some(slot) = write_buffers_slot {
                *slot = returned;
            }
        } else {
            // On failure, make the write buffers recoverable through
            // `take_write_buffers` whenever nothing keeps them pinned:
            // either the request never consumed the target (pre-wire
            // failure) or an error *response* handed the buffers back.
            let recovered = match target.take() {
                Some(arc) => WriteTarget::try_into_buffers(arc),
                None if !returned.is_empty() => Some(returned),
                None => None,
            };
            if let Some(buffers) = recovered {
                *self.write_buffers.lock().unwrap() = Some(buffers);
            }
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_write_buffers_recoverable_after_failed_call() {
        use crate::{SocketPoolConfig, services::MetaService as _};
        let ctx = crate::Context::create(&SocketPoolConfig::default()).unwrap();
        let client = Client::default();
        let mut buf = ctx.state.buffer_pool.allocate(64 * 1024).unwrap();
        buf.set_len(16);
        let wrapper = client.with_write_buffers(vec![buf]);
        // Invalid endpoint: the call fails before reaching the wire.
        let result = wrapper.list_methods(&ctx, &()).await;
        assert!(result.is_err());
        let recovered = wrapper.take_write_buffers().expect("buffers recoverable");
        assert_eq!(recovered.len(), 1);
        assert_eq!(recovered[0].len(), 16);
    }
}
