use crate::{Error, ErrorKind};

/// Runs a service handler future, converting a panic into an [`Error`].
///
/// Used by the code generated by `#[ruapc::service]`: without this, a
/// panicking handler would be silently swallowed by `tokio::spawn` and the
/// client would hang until its request timed out. With it, the client
/// receives an [`ErrorKind::HandlerPanic`] error response immediately.
///
/// Hidden from docs: this is macro plumbing, not a public API.
#[doc(hidden)]
pub async fn catch_handler_panic<F>(fut: F) -> std::result::Result<F::Output, Error>
where
    F: Future,
{
    use futures_util::FutureExt as _;

    // `AssertUnwindSafe` is appropriate here: the future is dropped on
    // panic, and the surrounding context only holds `Arc`s and channel
    // handles whose invariants do not depend on the handler completing.
    match std::panic::AssertUnwindSafe(fut).catch_unwind().await {
        Ok(output) => Ok(output),
        Err(panic) => {
            let msg = if let Some(s) = panic.downcast_ref::<&str>() {
                (*s).to_string()
            } else if let Some(s) = panic.downcast_ref::<String>() {
                s.clone()
            } else {
                "unknown panic payload".to_string()
            };
            tracing::error!("service handler panicked: {msg}");
            Err(Error::new(
                ErrorKind::HandlerPanic,
                format!("service handler panicked: {msg}"),
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_catch_handler_panic_ok() {
        let result = catch_handler_panic(async { 42 }).await;
        assert_eq!(result.unwrap(), 42);
    }

    #[tokio::test]
    async fn test_catch_handler_panic_str() {
        let result = catch_handler_panic(async { panic!("boom") }).await;
        let err = result.unwrap_err();
        assert_eq!(err.kind, ErrorKind::HandlerPanic);
        assert!(err.msg.contains("boom"));
    }

    #[tokio::test]
    async fn test_catch_handler_panic_string() {
        let value = 7;
        let result = catch_handler_panic(async move {
            assert_eq!(value, 8, "value mismatch");
        })
        .await;
        let err = result.unwrap_err();
        assert_eq!(err.kind, ErrorKind::HandlerPanic);
        assert!(err.msg.contains("value mismatch"));
    }
}
