[package]
name = "ruapc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
ruapc-macro = { version = "0.1.0", path = "../ruapc-macro" }

bitflags.workspace = true
foldhash.workspace = true
humantime-serde.workspace = true
serde.workspace = true
serde-inline-default.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
