name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: |
        cargo install cargo-llvm-cov cargo-nextest
        cargo llvm-cov nextest --all-features
        cargo llvm-cov report --cobertura --output-path target/llvm-cov-target/cobertura.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: SF-Zhou/ruapc
        files: target/llvm-cov-target/cobertura.xml

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: SF-Zhou/ruapc
        files: target/nextest/default/junit.xml
